---
name: 📝 Documentation Report
description: Use this template for reporting a documentation issue or submitting a feature request for documentation
title: "[docs]: "
labels: ["documentation"]

body:
- type: markdown
  attributes:
    value: >
      **Thank you for wanting to report a problem with Percept UI documentation!**
        Please fill out your suggestions below.
        
        ⚠ Verify first that your issue is not [already reported on GitHub][issue search].
        
        [issue search]: ../search?q=is%3Aissue&type=issues
        
- type: textarea
  attributes:
    label: Summary
    description: >
      Explain the problem briefly below, add suggestions to wording or structure.

    placeholder: >-
      I was reading the Percept UI documentation of Example component, and I found the wrong import method.
  validations:
    required: true

- type: dropdown
  attributes:
    label: Issue Type
    description: >
        Please select the type of the issue from the drop-down.
    options:
      - Documentation bug
      - Documentation feature/update
  validations:
    required: true

- type: input
  attributes:
    label: The entire URL of the documentation with the issue
    description: >
      Please provide a link to the documentation entry:
    placeholder: https://percept-ui.vercel.app/
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps to reproduce the issue
    description: >-
      Provide step by step instructions to reproduce the issue
    placeholder: >-
      1. Open docs, 2. Go to Component, 3. click on component...
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional Information
    description: >-
      Describe how this improves the documentation, e.g. before/after situation or screenshots.
    placeholder: >-
      When the improvement is applied, it makes it more straightforward to understand X.
  validations:
    required: false

- type: dropdown
  attributes:
    label: If the issue is confirmed, would you be willing to submit a pull request?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true


- type: markdown
  attributes:
    value: >
      Thank you for your collaboration!
...