name: Auto Assign Issues On Comment

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: (!github.event.issue.pull_request) && github.event.comment.body == 'take'
    concurrency:
      # Only run one a time per user
      group: ${{ github.actor }}-auto-assign-issue
    steps:
      - name: Check if issue can be assigned
        id: check-assignee
        run: |
          # Check if the user is already assigned to the issue
          RESPONSE=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees)
          if echo "$RESPONSE" | grep -q "${{ github.event.comment.user.login }}"; then
            echo "HTTP_CODE=204" >> $GITHUB_ENV
          else
            echo "HTTP_CODE=404" >> $GITHUB_ENV
          fi

      - name: Assign issue to commenter
        if: env.HTTP_CODE == '404'
        run: |
          # Assign the issue to the user who commented 'take'
          echo "Assigning issue #${{ github.event.issue.number }} to @${{ github.event.comment.user.login }}"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"assignees": ["${{ github.event.comment.user.login }}"]}' \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log failure to assign
        if: env.HTTP_CODE == '204'
        run: |
          # Log the failure to assign the issue
          echo "Issue #${{ github.event.issue.number }} cannot be assigned to @${{ github.event.comment.user.login }} because they are already assigned."
